### ISSUE TITLE
Server-side configuration of Models

### ISSUE THREAD

**Issue by GNSSYSTEMS-tg** [ghidoz/angular2-jsonapi#112]
As of right now, is it possible to dynamically define models by querying a server for its metadata? I don't think double maintenance is a good idea. Plus, my backend supports metadata descriptions for all models including types and defaults.

**Comment by GNSSYSTEMS-tg** [comment]
Ok, I've created a dummy that works like this:

~~~
@JsonApiModelConfig({
  type: 'DummyModel',
  meta: JsonApiMetaModel,
})
export class DummyModel extends JsonApiModel {
}
Reflect.defineMetadata('name', '', DummyModel.prototype, 'string');
Attribute()(DummyModel.prototype, 'name');
~~~

It seems to work. Anybody interested in this? I'd start with a prototype next month.

**Comment by HennerM** [comment]
You are right, currently there is no dynamic configuration of the models. 
Since all the attribute and attribute metadata added by the decorators gets saved with the `Reflect` API, I guess it is possible to add configuration dynamically, as you already found out on your own. FYI for proper resolving of relationships its also necessary to have a entry in the models map of JsonApiDatastoreConfig. 

The problem I can think of is how one would use the dynamic models. As of now every model has a TS class. With dynamic models the type safety of TS gets lost..
