### ISSUE TITLE
Using non json-api conform routes, eg. /login /logout

### ISSUE THREAD

**Issue by Birdr518** [ghidoz/angular2-jsonapi#169]
Hello,

i have a project using an API with some non json-api conform routes. 

Example:

For **login** i have to use a route `POST {{url}}/v1/login`
sending the credentials in the body 

```
{
  "data" : {
    "type" : "credentials",
    "attributes" : {
      "email" : "user@local.host",
      "password" : "xyz"
    }
  }
}
```

This structure can be easily implemented as a `credentials` object. 
But the response has not the type `credentials`, but the type `tokens` and the following form:

```
{
    "data": {
        "type": "tokens",
        "id": "",
        "attributes": {
            "object": "Token",
            "token_type": "Bearer",
            "expires_in": 86400,
            "token": "xyz",
            "refresh_token": "xyz"
        }
    },
    "meta": {
        "include": [],
        "custom": []
    }
}
```

Another problem is that for **logout** we do not use a route `DELETE {{url}}/v1/login`, but instead `DELETE {{url}}/v1/logout`
and an **empty body** (just sending the authentication header).
The problem is, how can i make a delete request on an object which has not been created before and even with an empty body without any attributes?

We have some more difficult routes with adding some items in non json-api conform relationsships of other objects. So that's why I am asking for that _simple_ route. If we cannot use the package for this example, we also cannot use it for the other ones.

Do you think there is a way to still use angular2-jsonapi for the example above?

**Comment by house-md** [comment]
@Birdr518 Hello,
from what you described you are using oAuth for your project, in our we had with backend developers exactly the same discussion about **pros** and **cons** of using Json Api standard in pre-login stages.

Due to some strict rules from both standards and other limitations (like different content-type headers or those you mentiones above) we decided to "split" our application into two stages:
**1.)** routes like login, registration, forgotten password etc. -> we **don't** use json-api and use standards for oAuth
**2.)** everything where is client authenticated (we have access to access/refresh token) we **use** json-api

Perks of this solutions are we are not tied up by two standards and doesn't need to overcomplicate our code. We can use pre-login routes (login, registration) without overcomplicated models and logic.

**Comment by baudday** [comment]
Any thoughts on action-specific routes on a resource? Something like `/resource/:id/send`. How would you handle that request?

**Comment by baudday** [comment]
This is great! Thanks. Do I just need the custom route to return the updated object in jsonapi format then?

**Comment by jacobbullock** [comment]
@baudday that is correct. I am doing that on an existing project and using the customUrl parameter is working great.
