### ISSUE TITLE
Push to array attributes do not set `hasDirtyAttributes`

### ISSUE THREAD

**Issue by hpawe01** [ghidoz/angular2-jsonapi#202]
When I have an **array** attribute in my resource, which is not a relationship, the following test fails:

```javascript
it('should recognize array push as dirty', () => {
  const DATA = {
    id: '1',
    attributes: {
      name: 'Daniele',
      surname: 'Ghidoli',
      date_of_birth: '1987-05-25',
      items: ['item 1'],
    }
  };
  const author: Author = new Author(datastore, DATA);
  author.items.push('item 2');
  expect(author.hasDirtyAttributes).toBeTruthy();
});
```

When I set the attribute via `author.items = ['item 1']`, `hasDirtyAttributes` is true.

I didn't have time to look through the code, but I guess, it has something to do with the change detection mechanism on the model.

I think both ways should work, as this behavior is (at least for me) inexplicable on the first look and cost me some time today (because the library didn't send any changes to the server although the attribute contained the changes).

**Comment by hpawe01** [comment]
I used `@Attribute() items: []`.

But I saw in the code, that, if `metadata.nested` is true, there will be an additional comparison, when `checkChanges()` is called. Has my problem something to do with nested fields?

**Comment by hpawe01** [comment]
The same is true for objects (e.g. `@Attribute() item: { name: string }`).

Maybe we should just say in the docs, that the model attributes should be treated as **immutable** objects, to make the change detection work.

**Comment by house-md** [comment]
try this 
```typescript
@NestedAttribute({converter: new JsonModelConverter(Array, {hasMany: true})})
item: Array<string>;
```
or 
```typescript
class Item extends JsonApiNestedModel{
@JsonApiAttribute()
name: string;
}

@NestedAttribute({converter: new JsonModelConverter(Item)})
item: Item;
```

there is problem with realtime catch of nested fields changes array or objects.

because when You have item = [1,2,3] and you do item = [1,2,3,4] value obviously changed, but and setter will be triggered, but item.push(4) will not give information about change and the same thing is with objects. and these things can be much more complex like array of Addresses. when you change for example street name in one address then whole array of addresses should be marked as dirty. I tried to do this with nested proxy 'trap' where behaviour would be the same as with @Attribute but It always ends up with infinite loop from JS call of methods. So in the end I went with actual solution where these @NestedAttribute fields are checked for changes in hasDirtyAttribute method.

**Comment by house-md** [comment]
I forgot tests for this solution are in src/converters/json-model/json-model.converter.spec.ts
Hope I tested all possible paths.

**Comment by hpawe01** [comment]
Thanks for your response. I changed it to 
```typescript
@NestedAttribute()
items: string[];
```
and it **works**!
Note, that I didn't need to define a converter and defined the array in another way. So maybe you could extend the [wiki files](https://github.com/ghidoz/angular2-jsonapi/wiki/Decorators) regarding this decorator?

Anyways, I'll close this issue, as it is solved by just using another decorator for array properties on my model.

**Comment by guy-roberts** [comment]
Thank you. I spent a day getting here, but your work around worked.
