### ISSUE TITLE
Infinite nested relationships

### ISSUE THREAD

**Issue by HennerM** [ghidoz/angular2-jsonapi#27]
in the README it says that this library resolves infinite levels of relationships, but I think I it's just 2 levels, beacuase in `JsonApiModel`  `syncRelationships()` is only called if the level is <= 1. Would there be any problem if this isn't limited?

**Comment by ghidoz** [comment]
Well, at the beginning I had to limit it, because otherwise it went into an infinite loop.

Then I implemented the storage, so that it resolves relationships, connecting objects by reference. This is what I mean with "infinite levels". If you have a book, that has an author, that has books... it's simply recursively infinite.
Now, with the storage, maybe there's no need for the limit anymore, I have to try.
