### ISSUE TITLE
Support Embedded Relationships

### ISSUE THREAD

**Issue by HennerM** [ghidoz/angular2-jsonapi#45]
I want to start a discussion about supporting creation of embedded relationships. Currently the JSON API specification doesn't allow to create more than one entity in one request, but there are multiple issues to support it (json-api/json-api#1089, json-api/json-api#795).

I already implemented it, but don't know if I should create a pull-request, because it's not in the official spec yet: https://github.com/HennerM/angular2-jsonapi/blob/compound-resource-creation/src/services/json-api-datastore.service.ts#L107

What are your opinions on this topic?

**Comment by reva2** [comment]
@HennerM I like it, because it's useful for real products. 

As I understand it's just a basic implementation that support Scenario A from (json-api/json-api#1089). It doesn't support updates (scenarios B) and multi-level nesting (scenario C). It would be great if you can implement missing features.
