### ISSUE TITLE
Possibility to customize structure of response

### ISSUE THREAD

**Issue by opium-draga** [ghidoz/angular2-jsonapi#66]
Hi guys, can you help me please ? I not sure if it issue or it problem of JSON API

Example of JSON API response 
```
{
  "success": true,
  "response": {
    "data": [
      {
        "type": "products",
        "id": "7",
        "attributes": {
          "id": "7",
          "urlCode": "regular-e-8713568281133",
          "title": "Sparta regular e e-bike"    
        },
        "links": [],
        "relationships": []
      }
    ]
  },
  "error": "",
  "ver": 1
}
```

As you can see, field **data** not in the root of response, and i have this error https://www.screencast.com/t/HFRquYLD. 
I see that in private method JsonApiDatastore::extractQueryData you trying to get it from root.
Are there any options to provide correct work with custom response?

**Comment by hameltomor** [comment]
Hi guys! I want override the method 'extractQueryData' in [https://github.com/ghidoz/angular2-jsonapi/blob/master/src/models/json-api.model.ts](https://github.com/ghidoz/angular2-jsonapi/blob/master/src/models/json-api.model.ts). I want change structure of response. I have own wrapper for result. At the moment I can't override this method, because it have the private modifiers. When I change private to protected, I could implemented my logic for extract data. Man, change pls it in your library and I will install the last version of project with protected.

**Comment by HennerM** [comment]
I am a bit concerned about adding this possibility. JSON-API describes itself as highly opinionated and therefore it makes sense to hold on the standard. 
On the other hand I understand that you are frustrated that this is not possible just because of the private modifier. If you still need this change I can maybe do it as a temporary workaround until we have a better long-term solution.

**Comment by HennerM** [comment]
Closed due to inactivity, feel free to reopen if this was done by mistake.
